### ISSUE TITLE
SHIELD can't find mysqldump binary on K8s

### ISSUE THREAD

**Issue by naveedahd** [shieldproject/helm#3]
**Issue description:**

Whenever a backup job is run, SHIELD helm deployment throws out the error below:

`Unable to exec '/var/vcap/packages/shield-mysql/bin/mysqldump': fork/exec /var/vcap/packages/shield-mysql/bin/mysqldump: no such file or directory`

**Cause/Reason:**

This is because SHIELD by default tries to find the mysqldump binary for BOSH releases. 

**Fix:**

A simple fix is to install the mysqldump binary at the initiation of the agent container. That installs the binary in `/usr/bin`. This path should be used/specified while configuring a backup job.

**Comment by jhunt** [comment]
There's two problems at work here:

1) We default plugin paths such that they work "out of the box" with the BOSH release.

2) We build the agent on the assumption that we would be able to compose filesystems however we see fit.  In BOSH this is easy - just add more jobs to the instance group to get new packages.  In Docker/Kubernetes it's much more difficult - despite all the things you can swtich out about a container, it's filesystem is fairly static.

Best course of would be:

- Modify `shield-agent` and allow it to specify new environment variables to be used in backup / restore operations, via a new top-level key called `env:`.

- Modify base SHIELD plugins to exec their helper binaries without a full path, and rely on `$PATH` instead.

- Modify the SHIELD docker images to bundle all of the required helper binaries for base plugins, or build a combinatorial series of docker images, i.e. `shieldproject/core-mysql`, `shieldproject/core-pgdump`, etc.

Note: these are all changes to https://github.com/shieldproject/shield itself.
